export const filterActions = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP'
};
export const filterActionsDiago = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP'
};
export const filterActionsFollowUp = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP'
};
